window_type : 'lung'
root_p : //zkh/appdata/RTDicom/Projectline_modelling_lung_cancer/
source_csv: //zkh/appdata/RTDicom/Projectline_modelling_lung_cancer/Users/Luis/CSVs/FinalDicomTable3.csv
save_path : //zkh/appdata/RTDicom/Projectline_modelling_lung_cancer/Users/Luis/CT_ITV_GTV_XBP_Nii_(170)/

structure_for_mask : None
image_generation_flag: True
mask_generation_flag: True

# ITV Labels
itv_tot_labels : ["ITV", "IGTV", "IgTV", "ITV1", "ITV2", "ITV3", "ITV totaal def", "2ITV", "ITV_TOT", "ITV_6000", "ITV_5100", "ITV_Totaal", "ITV_LBK", "ITV_LOK", "IGTV_6000"]
itv_tumor_labels : ["ITVtumor", "ITV_tumor", "ITVtumor def", "2ITV_tumor", "ITV-P", "ITVtumorA1", "ITV_tumor_LBK", "ITVtu", "IGTVp","IGTVtumor"]
itv_ln_labels : ["ITVklieren", "ITV_klier", "ITV_Klier", "ITVklieren def", "2ITV_klier", "ITV_n", "ITV_klier_LBK", "IGTVnode"]

# GTV Labels
gtv_tot_labels : ["GTV", "GTV1", "GTV2", "GTV3", "GTV totaal def", "2GTV", "GTV_TOT", "GTV_6000", "GTV_5100", "GTV_Totaal", "GTV_LBK", "GTV_LOK", "GTV_5000", "GTV_preop", "GTV_totaal", "GTVtotaal", "GTVnew", "GTV(op exp)", "GTVtumor_exp", "GTVtumor_exp_50->0"]
gtv_tumor_labels : ["GTVtumor", "GTV_tumor", "GTVtumor def", "2GTV_tumor", "GTV-P", "GTVtumorA1", "GTV_tumor_LBK", "GTV tumor", "GTVp", "GTVtu", "GTVtumor_insp","GTVt"]
gtv_ln_labels : ["GTVklieren", "GTV_klier", "GTV_Klier", "GTVklieren def", "2GTV_klier", "GTV_n", "GTV_klier_LBK", "GTVn", "GTVnode_exp", "GTVnodes_exp", "GTVnodes_exp_50->0", "GTVnodes_insp", "GTVklieren"]
